spring.application.name=GestioPro

# spring.datasource.url=jdbc:sqlite:database.db
# spring.datasource.driver-class-name=org.sqlite.JDBC
# spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.url=jdbc:postgresql://localhost:5332/dennis
spring.datasource.username=sa
spring.datasource.username=Pa55w0rd
spring.datasource.driver-class-name=org.postregresql.Driver

# spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true